---
- name: Init mongodb replica set
  hosts: app
  vars_files:
    - "vars/replica-{{mongo_version}}.yml"
  tasks:
    - name: Create root directories
      file: recurse=yes path="{{item}}" state=directory
      with_items:
        - "{{root}}/keys"
        - "{{root_data}}"

    - name: Create mongodb replica data directories
      file: path="{{root_data}}/{{item}}" state=directory
      with_items: "{{mongo_instance_ports}}"

    - name: Create key-file for replica instances internal comunication
      shell: openssl rand -base64 741 > mongodb-keyfile
      args:
        chdir: "{{root}}/keys"
        creates: "mongodb-keyfile"

    - name: Change keyfile group, user to be mongodb (999)
      file: path="{{item}}" mode=0600 owner=999 group=999
      with_items:
        - "{{root}}/keys"
        - "{{root}}/keys/mongodb-keyfile"
      tags:
        - "permissions"

    - name: Start first replica mongodb instance
      docker:
        name: "mongo-replica-{{mongo_version}}-{{mongo_master_port}}"
        image: "mongo:{{mongo_version}}"
        state: started
        hostname: "node-{{mongo_master_port}}"
        command: mongod --smallfiles
        restart_policy: always
        docker_api_version: 1.21
        volumes:
          - "{{root_data}}/{{mongo_master_port}}:/data/db"
          - "{{root}}/keys/mongodb-keyfile:/opt/keyfile/mongodb-keyfile"
        ports:
          - "{{mongo_master_port}}:27017"

    - name: Setup admin user for replica set
      mongodb_user:
        login_port: "{{mongo_master_port}}"
        database: admin
        name: admin
        password: password
        roles: "root"
        state: present

    - name: Stop first replica mongodb instance
      docker:
        name: "mongo-replica-{{mongo_version}}-{{mongo_master_port}}"
        image: "mongo:{{mongo_version}}"
        state: stopped
        docker_api_version: 1.21
